# Generated by Django 6.1 on 2026-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='special_requests',
            new_name='extra_details',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='airbnb_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_map_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='gps_tracking_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='guide_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='hospitality_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='photography_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_with_strangers',
            field=models.BooleanField(default=False),
        ),
    ]
