# Generated by Django 6.1 on 2026-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_payment_method_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
