# Generated by Django 6.1 on 2026-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_latitude_booking_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kids_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
