# Generated by Django 6.1 on 2026-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_kids_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_method',
            field=models.CharField(choices=[('BUS', '🚌 Bus'), ('TRAIN', '🚆 Train'), ('FLIGHT', '✈️ Flight'), ('CAR', '🚗 Car')], default='BUS', max_length=20),
        ),
    ]
