# Generated by Django 6.1 on 2026-09-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_travel_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travel_method',
            field=models.CharField(choices=[('BUS', ' Bus'), ('TRAIN', ' Train'), ('FLIGHT', ' Flight'), ('CAR', 'Car')], default='BUS', max_length=20),
        ),
    ]
