# Generated by Django 6.1 on 2026-09-01 17:52

import django.core.validators
import home.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[home.models.validate_destination_name])),
                ('location', models.CharField(max_length=150, validators=[home.models.validate_location])),
                ('description', models.TextField(validators=[home.models.validate_description])),
                ('image', models.ImageField(upload_to='destinations/', validators=[home.models.validate_image])),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'), message='Budget must be greater than ₹0.')])),
                ('season', models.CharField(max_length=100)),
                ('activities', models.CharField(max_length=300, validators=[home.models.validate_activities])),
                ('mood', models.CharField(choices=[('Relax', 'Relax'), ('Adventure', 'Adventure'), ('Family', 'Family'), ('Romantic', 'Romantic'), ('Nature', 'Nature'), ('Student', 'Student')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('guide_available', models.BooleanField(default=False)),
                ('photography_available', models.BooleanField(default=False)),
                ('google_map_available', models.BooleanField(default=False)),
                ('hospitality_available', models.BooleanField(default=False)),
                ('airbnb_available', models.BooleanField(default=False)),
                ('gps_tracking_available', models.BooleanField(default=False)),
                ('travel_with_strangers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
